### ISSUE TITLE
Scoring incorrect

### ISSUE THREAD

**Issue by cjensen506** [dacarlin/cribbage#3]
The def score_count(plays) is missing scoring of runs.
heels is missing

**Comment by djanders19** [comment]
It appears that most of the pegging-based scoring is missing in fact. I don't see code for scoring pairs, pair royals, double pair-royals, or 15s. Additionally, the game only awards 1 point for hitting 31 (should be 2) and does not score go's or "last cards". Details of all this scoring is [here](https://www.mastersofgames.com/rules/cribbage-rules.htm); I am working on a solve as part of a larger project.
